#!/usr/bin/env python3
"""Bake _neo.js — real near-Earth asteroid close approaches for the lab's
CLOSE ENCOUNTERS view.

Data: NASA/JPL SSD APIs (public domain, but NOT CORS-open — hence baked here
rather than fetched in-browser; the production widget should go through
proxy.bluishvoid.com / bvProxyJSON instead):
  cad.api  — close approaches to Earth within 10 lunar distances,
             45 days back to 120 days ahead of the bake date
  sbdb.api — per-object osculating elements + orbit class, so the lab can
             draw each asteroid's actual heliocentric orbit (where it came from)

    python3 build_neo.py
"""
import json, math, sys, time, datetime, pathlib, urllib.request, urllib.parse

today = datetime.date.today()
dmin = (today - datetime.timedelta(days=45)).isoformat()
dmax = (today + datetime.timedelta(days=120)).isoformat()

cad_url = ('https://ssd-api.jpl.nasa.gov/cad.api?dist-max=10LD'
           '&date-min=%s&date-max=%s&sort=date&fullname=true' % (dmin, dmax))
cad = json.load(urllib.request.urlopen(cad_url, timeout=30))
fields = cad['fields']
rows = [dict(zip(fields, r)) for r in cad.get('data', [])]
print('cad rows:', len(rows))

# keep the most interesting: sort by miss distance, cap, then re-sort by date
rows.sort(key=lambda r: float(r['dist']))
rows = rows[:18]
rows.sort(key=lambda r: r['jd'])

out = []
for r in rows:
    des = r['des']
    try:
        sb = json.load(urllib.request.urlopen(
            'https://ssd-api.jpl.nasa.gov/sbdb.api?sstr=' + urllib.parse.quote(des), timeout=30))
        els = {e['name']: float(e['value']) for e in sb['orbit']['elements']
               if e['value'] is not None}
        cls = sb['object']['orbit_class']['name']
        full = sb['object']['fullname'].strip()
    except Exception as ex:
        print('  skip', des, ex); continue
    h = float(r['h']) if r.get('h') else None
    diam_m = round(1329/math.sqrt(0.14) * 10**(-h/5) * 1000) if h else None
    out.append({
        'des': des, 'name': full, 'cd': r['cd'], 'jd': float(r['jd']),
        'au': round(float(r['dist']), 5),
        'ld': round(float(r['dist'])/0.002569, 1),
        'vrel': round(float(r['v_rel']), 1),
        'h': h, 'diam': diam_m, 'cls': cls,
        'els': {k: els.get(k) for k in ('a','e','i','om','w','ma','per')},
        'epoch': float(sb['orbit']['epoch']),
    })
    print('  ok', des, '|', cls, '| a=%.2f' % els.get('a', 0), '| %.1f LD' % (float(r['dist'])/0.002569))
    time.sleep(0.4)

p = pathlib.Path(__file__).resolve().parent / '_neo.js'
p.write_text('/* AUTO-GENERATED by build_neo.py — NASA/JPL SSD cad.api + sbdb.api.\n'
             '   Close approaches within 10 LD, %s → %s (baked %s). */\n'
             % (dmin, dmax, today.isoformat())
             + 'var NEO_ENCOUNTERS=' + json.dumps(out, separators=(',', ':')) + ';\n'
             + "var NEO_BAKED='" + today.isoformat() + "';\n")
print('wrote _neo.js:', len(out), 'objects')
