#!/usr/bin/env python3
"""Bake _tle.js from CelesTrak GP JSON (same bake-for-lab pattern as _neo.js).

Usage: curl the groups to /tmp first (or run the curls below), then run this.
  for g in stations visual gps-ops geo starlink; do
    curl -s "https://celestrak.org/NORAD/elements/gp.php?GROUP=$g&FORMAT=json" -o /tmp/tle_$g.json
  done

Starlink is ~11k objects; the lab shows an every-Nth sample (~400) and
reports the true total. Per-sat record (mean elements, enough for a lab
propagation): [name, epoch_ms, mean_motion rev/day, ecc, inc, raan, argp,
ma, launch_year (from OBJECT_ID intl designator)].
"""
import json, os, sys, datetime

SRC = sys.argv[1] if len(sys.argv) > 1 else "/tmp"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_tle.js")
GROUPS = ["stations", "visual", "gps-ops", "geo", "starlink",
          "cosmos-2251-debris", "iridium-33-debris", "fengyun-1c-debris"]
CAP = {"starlink": 400}

def rec(s):
    ep = datetime.datetime.fromisoformat(s["EPOCH"]).replace(tzinfo=datetime.timezone.utc)
    return [s["OBJECT_NAME"].strip(), int(ep.timestamp()*1000),
            round(s["MEAN_MOTION"], 8), round(s["ECCENTRICITY"], 7),
            round(s["INCLINATION"], 4), round(s["RA_OF_ASC_NODE"], 4),
            round(s["ARG_OF_PERICENTER"], 4), round(s["MEAN_ANOMALY"], 4),
            int(s["OBJECT_ID"][:4]) if s.get("OBJECT_ID") else None]

out, totals = {}, {}
for g in GROUPS:
    d = json.load(open(os.path.join(SRC, f"tle_{g}.json")))
    totals[g] = len(d)
    if g in CAP and len(d) > CAP[g]:
        step = len(d) / CAP[g]
        d = [d[int(i*step)] for i in range(CAP[g])]
    out[g] = [rec(s) for s in d]

stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%MZ")
with open(OUT, "w") as f:
    f.write(f"/* AUTO-GENERATED by build_tle.py — CelesTrak GP snapshot {stamp}.\n")
    f.write("   [name, epoch_ms, mean_motion rev/day, ecc, inc, raan, argp, ma] */\n")
    f.write("var TLE_STAMP = " + json.dumps(stamp) + ";\n")
    f.write("var TLE_TOTALS = " + json.dumps(totals) + ";\n")
    f.write("var TLE = " + json.dumps(out, separators=(",", ":")) + ";\n")
print(f"wrote {OUT}: " + ", ".join(f"{g} {len(out[g])}/{totals[g]}" for g in GROUPS))
