#!/usr/bin/env python3
"""Bake _dso.js — the Messier catalogue at true chart positions.

Positions/types come from SIMBAD (sim-tap ADQL), which has no CORS, so this is
baked the same way _starfield.js and _neo.js are. Equatorial RA/Dec is converted
to ecliptic here so the lab can plot straight through skyXY().
Run: python3 build_dso.py
"""
import urllib.request, urllib.parse, csv, io, math, json, sys

ADQL = """SELECT id.id, basic.ra, basic.dec, basic.otype_txt, allfluxes.V
FROM ident AS id JOIN basic ON id.oidref = basic.oid
LEFT JOIN allfluxes ON allfluxes.oidref = basic.oid
WHERE id.id LIKE 'M %'"""

# SIMBAD's otype codes collapsed to the four things worth drawing differently
def klass(t):
    t = (t or '').strip()
    if t in ('GlC',): return 'glob'
    if t in ('OpC','Cl*','As*'): return 'open'
    if t in ('PN',): return 'pneb'
    if t.startswith('G') or t in ('IG','GiG','GiP','GiC','AGN','Sy1','Sy2','LIN','SBG'): return 'gal'
    if t in ('SNR','HII','RNe','DNe','Neb','GNe','MoC','ISM','Cld'): return 'neb'
    return 'neb'

NAMES = {1:'CRAB NEBULA', 8:'LAGOON NEBULA', 11:'WILD DUCK CLUSTER',
         13:'HERCULES CLUSTER', 16:'EAGLE NEBULA', 17:'OMEGA NEBULA',
         20:'TRIFID NEBULA', 27:'DUMBBELL NEBULA', 31:'ANDROMEDA GALAXY',
         42:'ORION NEBULA', 44:'BEEHIVE CLUSTER', 45:'PLEIADES',
         51:'WHIRLPOOL GALAXY', 57:'RING NEBULA', 64:'BLACK EYE GALAXY',
         81:"BODE'S GALAXY", 82:'CIGAR GALAXY', 87:'VIRGO A',
         97:'OWL NEBULA', 101:'PINWHEEL GALAXY', 104:'SOMBRERO GALAXY'}

def ecl(ra, dec):
    e = math.radians(23.4393)
    a, d = math.radians(ra), math.radians(dec)
    sb = math.sin(d)*math.cos(e) - math.cos(d)*math.sin(e)*math.sin(a)
    lat = math.degrees(math.asin(max(-1, min(1, sb))))
    lon = math.degrees(math.atan2(math.sin(a)*math.cos(e) + math.tan(d)*math.sin(e),
                                  math.cos(a))) % 360
    return lon, lat

url = 'https://simbad.u-strasbg.fr/simbad/sim-tap/sync?' + urllib.parse.urlencode(
    {'request':'doQuery','lang':'adql','format':'csv','maxrec':'400','query':ADQL})
txt = urllib.request.urlopen(url, timeout=90).read().decode()
seen = {}
for r in csv.DictReader(io.StringIO(txt)):
    ident = (r.get('id') or '').strip()
    if not ident.startswith('M '): continue
    num = ident[2:].strip()
    if not num.isdigit(): continue
    n = int(num)
    if n in seen: continue
    try: ra, dec = float(r['ra']), float(r['dec'])
    except Exception: continue
    try: v = float(r.get('V') or 'nan')
    except Exception: v = float('nan')
    lon, lat = ecl(ra, dec)
    seen[n] = [n, round(lon,2), round(lat,2), klass(r.get('otype_txt')),
               None if v != v else round(v,1), NAMES.get(n)]
rows = [seen[k] for k in sorted(seen)]
if len(rows) < 100:
    sys.exit('only %d objects parsed — refusing to bake a partial catalogue' % len(rows))

with open('_dso.js','w') as f:
    f.write('/* AUTO-GENERATED by build_dso.py — the Messier catalogue.\n'
            '   Source: SIMBAD (CDS, Strasbourg). Positions converted to ecliptic here.\n'
            '   Format: DSO = [M#, eclLon, eclLat, class, Vmag|null, name|null][]\n'
            '   class: gal | glob | open | pneb | neb                              */\n')
    f.write('var DSO=[\n')
    for r in rows:
        nm = 'null' if r[5] is None else '"%s"' % r[5]
        v  = 'null' if r[4] is None else r[4]
        f.write('[%d,%.2f,%.2f,"%s",%s,%s],\n' % (r[0], r[1], r[2], r[3], v, nm))
    f.write('];\n')
print('baked _dso.js with %d objects' % len(rows))
from collections import Counter
print(Counter(r[3] for r in rows))
