#!/usr/bin/env python3
"""Regenerate _planetcore.js + _planetcore.css from index.html.

Pulls the LIVE planet-insight popup system out of the site so the solar
system lab opens the exact same popups the dashboard shows. Run from
_solarlab/ after any popup change on the site:

    python3 extract_planetcore.py

- _planetcore.js  = astro math (rad/deg/julianDay/ORB/kepler/planetRaDec/
                    moonRaDec/altAz...) + PLANET_MOONS/PLANET_DATA/
                    SPACE_MISSIONS + the whole popup stack (_bvArmBack,
                    _closePlanetPopup, _openInsightModal, _rewirePlanetTabs,
                    _tabifyPlanetInsight, showPlanetInsight). Extracted as
                    plain globals (no IIFE) for the lab page.
                    Lab must define LOCATION before loading this file's
                    consumers are called (popup reads LOCATION.lat/lon).
- _planetcore.css = hz-card row/head/footer styles + the planet-insight
                    modal styles (tab bar, light-theme inline-color remaps,
                    planet-modal-open scroll lock).
"""
import sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
html = (root / 'index.html').read_text()

def cut(label, start_anchor, end_anchor, include_end=True):
    s = html.find(start_anchor)
    if s < 0:
        sys.exit('anchor not found: %s (start of %s)' % (start_anchor[:40], label))
    e = html.find(end_anchor, s)
    if e < 0:
        sys.exit('anchor not found: %s (end of %s)' % (end_anchor[:40], label))
    if include_end:
        e += len(end_anchor)
    return html[s:e]

# ---- JS ----
astro = cut('astro math',
            '  function rad(d){',
            '  function computeVisibilityWindows', include_end=False)
popup = cut('popup stack',
            '  var PLANET_INTERIOR=',
            '  window.showPlanetInsight = showPlanetInsight;')
showers = cut('meteor showers',
              '  var METEOR_SHOWERS = [',
              '\n  ];')
hdr = ('/* AUTO-GENERATED by extract_planetcore.py from index.html — do not edit by hand.\n'
       '   Plain globals (site IIFE stripped) so the solar lab can open the real popups.\n'
       '   Page must define: var LOCATION = {lat:..., lon:...}; */\n')
(root / '_solarlab' / '_planetcore.js').write_text(hdr + astro + '\n' + popup + '\n' + showers + '\n')

# ---- CSS ----
cards = cut('hz-card styles',
            '  /* ── Card header ── */',
            '  /* ── Tag pills ── */', include_end=False)
modal = cut('planet modal styles',
            '  html.planet-modal-open,',
            '  #planet-insight-popup .planet-tab-panel.active {\n    display: block;\n  }')
hero = cut('planet hero styles',
           '  #planet-insight-popup .planet-hero {',
           '  /* ── Light-theme overrides removed ── */', include_end=False)
# The site keeps these two inside larger unrelated @media blocks — restate them.
mobile = ('  @media (max-width: 900px) {\n'
          '    #planet-insight-popup .planet-columns { grid-template-columns: repeat(2, minmax(0, 1fr)) !important; }\n'
          '    .bv-popup-x { width: 46px !important; height: 46px !important; font-size: 30px !important; background: rgba(127,127,127,.10); }\n'
          '    .bv-popup-x:active { background: rgba(127,127,127,.22); }\n'
          '    .bv-popup-closebar { padding: 40px 14px 0 !important; }\n'
          '  }\n')
hdrc = '/* AUTO-GENERATED by extract_planetcore.py from index.html — do not edit by hand. */\n'
(root / '_solarlab' / '_planetcore.css').write_text(hdrc + cards + '\n' + modal + '\n' + hero + '\n' + mobile)

print('wrote _planetcore.js (%d bytes) and _planetcore.css (%d bytes)' % (
    (root / '_solarlab' / '_planetcore.js').stat().st_size,
    (root / '_solarlab' / '_planetcore.css').stat().st_size))
